# Generated by Django 4.0.5 on 2022-06-27 17:42

import MiniProjects.utils.changeImageName
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProjectsCardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Project Name')),
                ('path', models.SlugField(max_length=500, verbose_name='Slug Path')),
                ('image', models.ImageField(upload_to='', verbose_name=MiniProjects.utils.changeImageName.changePhotoNameMiniProjects)),
                ('description', models.CharField(max_length=10000, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Mini Project Card',
                'verbose_name_plural': 'Mini Project Card Lists',
            },
        ),
    ]
