# Generated by Django 4.0.5 on 2022-07-03 04:39

import Accounts.utils.changeImageName
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12, verbose_name='Mobile Number')),
                ('bio', models.CharField(max_length=1200, verbose_name='Bio')),
                ('birthday', models.DateField(verbose_name='BirthDay')),
                ('profile_picture', models.ImageField(upload_to=Accounts.utils.changeImageName.changeProfilePictureName, verbose_name='Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
