# Generated by Django 4.0.5 on 2022-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='post_rate',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='Rate'),
        ),
    ]
