# Generated by Django 4.0.5 on 2022-06-27 10:51

import blog.utils.changeImageName
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='mainImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=blog.utils.changeImageName.changePhotoNameBlogImage),
        ),
        migrations.AddField(
            model_name='blogpostimage',
            name='title',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=blog.utils.changeImageName.changePhotoNamePostGallery),
        ),
    ]
