# Generated by Django 4.0.5 on 2022-06-27 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_mainimage_blogpostimage_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcomment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 15, 26, 9, 566810), verbose_name='Date'),
        ),
    ]
