# Generated by Django 4.0.5 on 2022-06-27 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpostcomment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostcomment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 27, 17, 13, 19, 76450, tzinfo=utc), verbose_name='Date'),
        ),
    ]
