# Generated by Django 4.0.5 on 2022-06-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarousel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
