# Generated by Django 4.0.5 on 2022-06-25 12:05

import Home.utils.changePictureNameForModel
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_homecarousel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecarousel',
            name='image',
            field=models.ImageField(upload_to=Home.utils.changePictureNameForModel.changePhotoName, verbose_name='Image'),
        ),
    ]
