# Generated by Django 4.0.5 on 2022-06-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_homecarousel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecarousel',
            options={'verbose_name': 'Home Carousel', 'verbose_name_plural': 'Home Carousel Table'},
        ),
    ]
