# Generated by Django 4.0.5 on 2022-06-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockscissorspaper',
            name='loseCount',
            field=models.IntegerField(default=0, verbose_name='Lose'),
        ),
        migrations.AlterField(
            model_name='rockscissorspaper',
            name='winCount',
            field=models.IntegerField(default=0, verbose_name='Win'),
        ),
    ]
