# Generated by Django 4.0.5 on 2022-06-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_alter_rockscissorspaper_losecount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rockscissorspaper',
            options={'verbose_name': 'Rock Scissors Paper', 'verbose_name_plural': 'Rock Scissors Paper Table'},
        ),
    ]
